[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "edaSQL"
authors = [{name = "TamilSelvan", email = "selva221724@gmail.com"}]
dynamic = ["version", "description"]
